# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapCatalog
                                 A QGIS plugin
 Map Catalog and Line Management Plugin for QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-16
        copyright            : (C) 2025 by Muhammad Aldien Said
        email                : aldien03@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapCatalog class from file MapCatalog.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MapCatalog import MapCatalog
    return MapCatalog(iface)
