# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapCatalog_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportSPSDockWidgetBase(object):
    def setupUi(self, ImportSPSDockWidgetBase):
        ImportSPSDockWidgetBase.setObjectName("ImportSPSDockWidgetBase")
        ImportSPSDockWidgetBase.resize(453, 707)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.openConfigpushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.openConfigpushButton.setObjectName("openConfigpushButton")
        self.verticalLayout.addWidget(self.openConfigpushButton)
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.selectMapCatalogcomboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.selectMapCatalogcomboBox.setObjectName("selectMapCatalogcomboBox")
        self.horizontalLayout_2.addWidget(self.selectMapCatalogcomboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImportLinepushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.ImportLinepushButton.setObjectName("ImportLinepushButton")
        self.horizontalLayout.addWidget(self.ImportLinepushButton)
        self.DeleteLinepushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.DeleteLinepushButton.setObjectName("DeleteLinepushButton")
        self.horizontalLayout.addWidget(self.DeleteLinepushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fgspspinBox = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.fgspspinBox.setMinimum(1000)
        self.fgspspinBox.setMaximum(9999)
        self.fgspspinBox.setObjectName("fgspspinBox")
        self.horizontalLayout_3.addWidget(self.fgspspinBox)
        self.lgspspinbox = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.lgspspinbox.setMinimum(1001)
        self.lgspspinbox.setMaximum(9999)
        self.lgspspinbox.setObjectName("lgspspinbox")
        self.horizontalLayout_3.addWidget(self.lgspspinbox)
        self.UpdateLinePushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.UpdateLinePushButton.setObjectName("UpdateLinePushButton")
        self.horizontalLayout_3.addWidget(self.UpdateLinePushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.checkOverlappushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.checkOverlappushButton.setObjectName("checkOverlappushButton")
        self.verticalLayout_2.addWidget(self.checkOverlappushButton)
        ImportSPSDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(ImportSPSDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(ImportSPSDockWidgetBase)

    def retranslateUi(self, ImportSPSDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        ImportSPSDockWidgetBase.setWindowTitle(_translate("ImportSPSDockWidgetBase", "Modify Map Catalog"))
        self.label.setText(_translate("ImportSPSDockWidgetBase", "Map Catalog"))
        self.openConfigpushButton.setText(_translate("ImportSPSDockWidgetBase", "Open Config"))
        self.label_2.setText(_translate("ImportSPSDockWidgetBase", "Select Map Catalog Layer:"))
        self.ImportLinepushButton.setText(_translate("ImportSPSDockWidgetBase", "Import SPS"))
        self.DeleteLinepushButton.setText(_translate("ImportSPSDockWidgetBase", "Delete Line"))
        self.fgspspinBox.setPrefix(_translate("ImportSPSDockWidgetBase", "FGSP "))
        self.lgspspinbox.setPrefix(_translate("ImportSPSDockWidgetBase", "LGSP "))
        self.UpdateLinePushButton.setText(_translate("ImportSPSDockWidgetBase", "Update Line"))
        self.checkOverlappushButton.setText(_translate("ImportSPSDockWidgetBase", "Remove Overlap"))
